import { Button, LineEdit, HorizontalBox, Spinner, ListView } from "std-widgets.slint";
import { Theme } from "theme.slint";
import { UserItem } from "structs.slint";
import { UserRow } from "user_row.slint";

export component ListPage inherits Rectangle {
    in-out property <string> search-query: "a";
    in-out property <[UserItem]> user-list;
    in-out property <bool> is-searching: false;

    callback search-requested(string);
    callback user-selected(int);

    background: Theme.bg-primary;

    VerticalLayout {
        width: 100%;
        height: 100%;
        padding: 0;
        
        HorizontalBox {
            height: 60px;
            padding-left: Theme.padding;
            padding-right: Theme.padding;
            alignment: center;

            // Title
            Text {
                text: "GitHub Users";
                font-size: 22px;
                color: Theme.text-primary;
                horizontal-alignment: center;
                vertical-alignment: center;
            }
        }
    
        // Search bar
        HorizontalBox {
            width: parent.width;
            height: 40px;
            spacing: 8px;
            padding-left: Theme.padding;
            padding-right: Theme.padding;
    
            LineEdit {
                text <=> root.search-query;
                placeholder-text: "Search users...";
                accepted => {
                    root.search-requested(root.search-query);
                }
            }
    
            Button {
                text: root.is-searching ? "..." : "Search";
                enabled: !root.is-searching;
                clicked => {
                    root.search-requested(root.search-query);
                }
            }
        }
    
        HorizontalBox {
            width: parent.width;
            height: parent.height - 60px - 40px;
            padding-left: Theme.padding;
            padding-right: Theme.padding;

            // User list
            ListView {
                for item[idx] in root.user-list : UserRow {
                    login: item.login;
                    avatar: item.avatar;
                    clicked => {
                        root.user-selected(idx);
                    }
                }
            }
        }
    }

    // Spinner overlay
    Rectangle {
        visible: root.is-searching;
        x: Theme.padding;
        y: 100px;
        width: parent.width - 48px;
        height: parent.height - 60px - 40px;
        background: Theme.bg-primary;
        Spinner { indeterminate: true; }
    }
}
