import { Theme } from "../theme.slint";
import { RepoItem } from "../structs.slint";

export component RepoCard inherits Rectangle {
    in-out property <RepoItem> repo;
    
    callback clicked();

    background: Theme.bg-card;
    border-radius: Theme.radius-md;
    clip: true;

    VerticalLayout {
        padding: Theme.padding;
        alignment: start;
        spacing: 4px;

        HorizontalLayout {
            alignment: space-between;
            
            Text {
                text: root.repo.name;
                color: Theme.text-primary;
                font-size: 14px;
                font-weight: 700;
            }

            Text {
                text: "⭐ " + root.repo.stars;
                color: Theme.accent;
                font-size: 12px;
                font-weight: 600;
            }
        }

        if root.repo.description != "" : Text {
            text: root.repo.description;
            color: Theme.text-dim;
            font-size: 12px;
            wrap: word-wrap;
            overflow: elide;
            vertical-alignment: top;
        }

        if root.repo.language != "" : Text {
            text: "● " + root.repo.language;
            color: Theme.text-subtle;
            font-size: 11px;
        }
    }

    TouchArea {
        clicked => { root.clicked(); }
        mouse-cursor: pointer;
    }
}
